version: '3.8'

services:
  app_python:
    image: aldeeyar/lab3:latest
    ports:
      - 80:80
    networks:
      - app_python
      - monitoring
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki/
      - ${PWD}/config/loki:/etc/loki
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  promtail:
    image: grafana/promtail:2.6.1
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/config/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - app_python
      - monitoring

    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ${PWD}/config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000

    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  prometheus:
    mem_limit: 200m
    image: prom/prometheus:v2.39.1
    volumes:
      - ${PWD}/config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitoring
    ports:
      - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
        tag: "{{.ImageName}}|{{.Name}}"
networks:
  app_python:
  monitoring:

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  prometheus-data: