version: "3"

networks:
    loki:

services:
    app_python:
        image: aldeeyar/lab2:latest
        container_name: app_python
        ports:
            - "80:80"

    loki:
        image: grafana/loki:2.6.1
        ports:
            - "3100:3100"
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - loki

    promtail:
        image: grafana/promtail:2.6.1
        volumes:
            - /var/log:/var/log
        command: -config.file=/etc/promtail/config.yml
        networks:
            - loki

    grafana:
        image: grafana/grafana:latest
        ports:
            - "3000:3000"
        networks:
            - loki
