apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab9
  labels:
    app: lab9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab9
  template:
    metadata:
      labels:
        app: lab9
    spec:
      containers:
      - name: lab9
        image: aldeeyar/lab2
        ports:
        - containerPort: 80